version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080" # forward app port
    env_file:
      - .env
    depends_on:
      - dragonfly
      - minio
    restart: always

  dragonfly:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - ./data/dragonfly:/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # forward s3 port
      - "9001:9001" # forward console port
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data

  postgres:
    image: postgres
    ports:
      - "5432:5432" # forward postgres port
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
