version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080" # forward app port
    env_file:
      - .env
    depends_on:
      - db
      - minio

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432" # forward postgres port
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # forward s3 port
      - "9001:9001" # forward console port
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
